--- #YAML:1.0
name:                CatalystX-CRUD
version:             0.23
abstract:            CRUD framework for Catalyst applications
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Catalyst::Component::ACCEPT_CONTEXT: 0
    Catalyst::Exception:           0
    Catalyst::Runtime:             0
    Class::Accessor::Fast:         0
    Data::Dump:                    0
    Data::Pageset:                 0
    NEXT:                          0
    Path::Class::File:             0
    Sort::SQL:                     0.03
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Peter Karman <perl@peknet.com>
