# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CatalystX-CRUD
version:      0.29
version_from: lib/CatalystX/CRUD.pm
installdirs:  site
requires:
    Catalyst::Component::ACCEPT_CONTEXT: 0
    Catalyst::Exception:           0
    Catalyst::Runtime:             0
    Class::Accessor::Fast:         0
    Class::C3:                     0
    Data::Dump:                    0
    Data::Pageset:                 0
    Path::Class::File:             0
    Sort::SQL:                     0.03
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
